name: woo-aras-setup.sh CI

on:
  push:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
	  - 'tmp/**'
	  - '.lck/**'
      - '**.md'
      - 'CHANGELOG'
  pull_request:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
	  - 'tmp/**'
	  - '.lck/**'
      - '**.md'
      - 'CHANGELOG'

permissions:
  contents: read

jobs:
  run_tests:
     matrix:
        os: [ubuntu-latest ]
	 runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      run: |
         chmod +x ./woocommerce-aras-kargo/woo-aras-setup.sh
         ./woocommerce-aras-kargo/woo-aras-setup.sh
      shell: bash
