name: woo-aras-setup.sh CI

on:
  push:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
      - 'tmp/**'
      - '.lck/**'
      - '**.md'
      - 'CHANGELOG'
      - 'woocommerce-aras-cargo.sh'
  pull_request:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
      - 'tmp/**'
      - '.lck/**'
      - '**.md'
      - 'CHANGELOG'
      - 'woocommerce-aras-cargo.sh'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - 'ubuntu:latest'
    container: ${{ matrix.container }}
    name: woo-aras-setup.sh on ${{ matrix.container }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: start woo-aras-setup.sh testing
        run: |
          chmod +x "${GITHUB_WORKSPACE}/woo-aras-setup.sh"
          chmod +x "${GITHUB_WORKSPACE}/woocommerce-aras-cargo.sh"
          export github_2023=1
          apt-get -y update
          apt-get -y install curl iproute2
          yes | bash -x "${GITHUB_WORKSPACE}/woo-aras-setup.sh"
          shell: bash
