name: woo-aras-setup.sh CI

on:
  push:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
      - 'tmp/**'
      - '.lck/**'
      - '**.md'
      - 'CHANGELOG'
  pull_request:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
      - 'tmp/**'
      - '.lck/**'
      - '**.md'
      - 'CHANGELOG'

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - 'debian:latest'
          - 'ubuntu:latest'
          - 'fedora:latest'
          - 'centos:latest'
          - 'manjarolinux/build'
          - 'gentoo/stage3'
          - 'arch:latest'
          - 'oraclelinux:9'
          - 'opensuse/leap:latest'
          - 'opensuse/tumbleweed:latest'
    container: ${{ matrix.container }}
    name: woo-aras-setup.sh on ${{ matrix.container }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Run woo-aras-setup.sh
        run: |
          chmod +x "${GITHUB_WORKSPACE}/woo-aras-setup.sh"
          "${GITHUB_WORKSPACE}/woo-aras-setup.sh
          shell: bash
