name: woo-aras-setup.sh CI

on:
  push:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
      - 'tmp/**'
      - '.lck/**'
      - '**.md'
      - 'CHANGELOG'
  pull_request:
    paths-ignore:
      - 'custom-order-status-package/**'
      - 'emails/**'
      - 'miscellaneous/**'
      - 'tmp/**'
      - '.lck/**'
      - '**.md'
      - 'CHANGELOG'

permissions:
  contents: read

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest ]
    name:  woo-aras-setup.sh on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
          chmod +x ${{ github.action_path }}/woo-aras-setup.sh
          ${{ github.action_path }}/woo-aras-setup.sh
          shell: bash
